import "server-only";

import { randomUUID } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { v2 as cloudinary } from "cloudinary";

import { validateCatalogueImage } from "@/features/catalogue/image-validation";
import { serverEnvironment } from "@/lib/env/server";

export type StoredCatalogueImage = Readonly<{
  url: string;
  width: number;
  height: number;
  storageProvider: "local_demo" | "cloudinary";
  storageKey: string;
}>;

function configureCloudinary(): void {
  /*
   * Environment validation guarantees these values whenever the Cloudinary
   * adapter is selected. Keeping configuration here avoids importing the
   * privileged SDK or credentials into any Client Component.
   */
  cloudinary.config({
    cloud_name: serverEnvironment.CLOUDINARY_CLOUD_NAME,
    api_key: serverEnvironment.CLOUDINARY_API_KEY,
    api_secret: serverEnvironment.CLOUDINARY_API_SECRET,
    secure: true,
  });
}

async function storeInCloudinary(
  image: Awaited<ReturnType<typeof validateCatalogueImage>>,
): Promise<StoredCatalogueImage> {
  configureCloudinary();

  const dataUri = `data:image/${image.extension === "jpg" ? "jpeg" : image.extension};base64,${Buffer.from(image.bytes).toString("base64")}`;
  const result = await cloudinary.uploader.upload(dataUri, {
    resource_type: "image",
    type: "upload",
    folder: serverEnvironment.CLOUDINARY_FOLDER,
    use_filename: false,
    unique_filename: true,
    overwrite: false,
    /*
     * Cloudinary decodes the validated input and creates a clean managed
     * derivative. Stripping embedded profiles removes avoidable EXIF/location
     * metadata while preserving the catalogue pixels.
     */
    transformation: [{ flags: "strip_profile" }],
  });

  if (
    !result.secure_url.startsWith("https://res.cloudinary.com/") ||
    !result.public_id.startsWith(`${serverEnvironment.CLOUDINARY_FOLDER}/`)
  ) {
    throw new Error("Cloudinary returned an invalid catalogue asset identity.");
  }

  return {
    url: result.secure_url,
    width: result.width,
    height: result.height,
    storageProvider: "cloudinary",
    storageKey: result.public_id,
  };
}

export async function storeCatalogueImage(
  file: File,
): Promise<StoredCatalogueImage> {
  const image = await validateCatalogueImage(file);

  if (serverEnvironment.MEDIA_STORAGE_PROVIDER === "cloudinary") {
    return storeInCloudinary(image);
  }

  /*
   * Local public-directory storage exists only for development and the
   * resettable portfolio demo. It is intentionally refused for a customer
   * deployment: application filesystems are usually ephemeral, cannot provide
   * storage-level least privilege, and are not an acceptable durable catalogue
   * source. Customer deployments use the Cloudinary adapter instead.
   */
  const directory = path.join(process.cwd(), "public", "uploads", "catalogue");
  await mkdir(directory, { recursive: true });
  const filename = `${randomUUID()}.${image.extension}`;
  await writeFile(path.join(directory, filename), image.bytes, { flag: "wx" });

  return {
    url: `/uploads/catalogue/${filename}`,
    width: image.width,
    height: image.height,
    storageProvider: "local_demo",
    storageKey: filename,
  };
}

export async function removeCatalogueImage(
  image: Pick<StoredCatalogueImage, "storageProvider" | "storageKey">,
): Promise<void> {
  if (image.storageProvider === "local_demo") {
    /*
     * Local cleanup accepts only filenames generated by this adapter and
     * resolves the final path under the fixed catalogue directory. It never
     * treats a database value as an arbitrary filesystem path.
     */
    if (!/^[0-9a-f-]{36}\.(?:jpg|png|webp)$/i.test(image.storageKey)) {
      throw new Error("Refusing to delete an invalid local catalogue key.");
    }

    const directory = path.resolve(
      process.cwd(),
      "public",
      "uploads",
      "catalogue",
    );
    const target = path.resolve(directory, image.storageKey);
    if (path.dirname(target) !== directory) {
      throw new Error("Refusing to delete media outside the catalogue folder.");
    }

    try {
      await unlink(target);
    } catch (error) {
      if (
        !(error instanceof Error) ||
        !("code" in error) ||
        error.code !== "ENOENT"
      ) {
        throw error;
      }
    }
    return;
  }

  const expectedPrefix = `${serverEnvironment.CLOUDINARY_FOLDER}/`;
  if (!image.storageKey.startsWith(expectedPrefix)) {
    throw new Error("Refusing to delete media outside the catalogue folder.");
  }

  configureCloudinary();
  const result = await cloudinary.uploader.destroy(image.storageKey, {
    resource_type: "image",
    type: "upload",
    invalidate: true,
  });

  if (!["ok", "not found"].includes(String(result.result))) {
    throw new Error("Cloudinary did not confirm catalogue asset deletion.");
  }
}
